version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-library-app
    environment:
      POSTGRES_DB: library_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
