server:
  port: 8080

spring:
  application:
    name: library-app
  datasource:
    url: jdbc:postgresql://localhost:5432/library_app_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
